@startuml
participant App
participant "EHR with Authorization Server" as EHR
participant "FHIR Server" as FHIR

opt  1. Precondition: Client Registration
    App ->> EHR: (may be out of band)
end
alt 2. EHR Launch
    EHR->>EHR: EHR user \nlaunches app
    EHR->> App: Launch request
else 2. Standalone Launch
    App->>App: App user \nconnects to EHR
end
App ->> FHIR: 3. Discovery request
FHIR ->> App: 3. Discovery response
App ->> EHR: 4. Authorization request
opt
    EHR->> EHR: 4. EHR incorporates user input\ninto authorization decision
end
alt Granted
    EHR ->> App: 4. Authorization granted
    App ->> FHIR: 5.,7. Access token request
    EHR ->> App: 5.,7. Access token response
    App ->> FHIR: 6. Request Resources
else Denied
    EHR ->> App: 4. Authorization error
end
@enduml
