resourceType: ValueSet
id: patient-access-brand-category
url: 'http://hl7.org/fhir/smart-app-launch/ValueSet/patient-access-brand-category'

name: PatientAccessBrandCategoryValueSet
title: Patient Access Brand Category Value Set
status: active
experimental: false
date: '2023-03-05T22:40:04-08:00'

description: Categorizes a PatientAccessBrand into high-level taxonomy

compose:
  include:
    - system: >-
        http://hl7.org/fhir/smart-app-launch/CodeSystem/patient-access-brand-category